Feature branch
nilab-khwaja/my-portfolio pull request #2
Opened 2023-02-16 10:29 UTC by nilab-khwaja

end first part of my-portfolio

2023-02-16 10:57 UTC, franclobo requested changes
Hi @nilab-khwaja, 

# ♻️ Required Changes ♻️

![so-close-jim-halpert](https://user-images.githubusercontent.com/58642949/219346424-d54fa3bd-39a7-4f58-a0fe-0916aa01be22.gif)

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- No linter errors ✔️ 
- Correct Github flow ✔️ 
- Good use of tags 💯 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-16 10:57 UTC, franclobo commented on README.md
> +> Describe your project in 1 or 2 sentences.
For a professional README file:
- [ ] Please 🙏🏽 remove the guidelines it helps you to know what you should do in each section.
- [ ] Please 🙏🏽 describe what your portfolio project is about.

2023-02-16 10:57 UTC, franclobo commented on README.md
> +> Describe between 1-3 key features of the application.
- [ ] Please 🙏🏽 remove the guidelines it helps you to know what you should do in each section for a professional README file.

2023-02-16 10:57 UTC, franclobo commented on README.md
> +> Describe how a new developer could make use of your project.
- [ ] Please 🙏🏽 remove the guidelines it helps you to know what you should do in each section for a professional README file.

2023-02-16 10:57 UTC, franclobo commented on README.md
> +> Mention all of the collaborators of this project.
- [ ] Please 🙏🏽 remove the guidelines it helps you to know what you should do in each section for a professional README file.

2023-02-16 10:57 UTC, franclobo commented on README.md
> +> Describe 1 - 3 features you will add to the project.
- [ ] Please 🙏🏽 remove the guidelines it helps you to know what you should do in each section for a professional README file.

2023-02-16 10:57 UTC, franclobo commented on README.md
> +<p align="right">(<a href="#readme-top">back to top</a>)</p>
For a professional README file:
- [ ] This is an optional section if you don't have questions to answer it could be better to remove this section from your README.

2023-02-16 10:57 UTC, franclobo commented on README.md
> +  <img src="murple_logo.png" alt="logo" width="140"  height="auto" />
- [ ] Kindly remove the Microverse logo or replace it with your own for a professional README file.

2023-02-16 10:57 UTC, franclobo commented on index.html
> +            <div class="logo"><h3>Logo</h3></div>
- [ ] This logo is a link, please 🙏🏽 use the `a` tag for best practices of HTML & CSS.

2023-02-16 10:57 UTC, franclobo commented on styles.css
> +  background-image: url('img/header-shapes\ mobile@2x.jpg');
- [ ] Please correct your styles to match the Figma template: use the guides from the Figma template for the margins, font family, font size, etc 👇🏽 

| Figma template | Your design |
|---|---|
| ![image](https://user-images.githubusercontent.com/58642949/219333322-8f3e2cd9-eb12-4756-b9af-51fc141246c8.png) | ![image](https://user-images.githubusercontent.com/58642949/219343709-2a2d2fc2-697f-49d5-90c5-4d91c430fc59.png) |

2023-02-16 10:57 UTC, franclobo commented on styles.css
> +  font-family: 'Courier New', Courier, monospace;
- [ ] Please 🙏🏽  import the font family Poppins at the beginning of your CSS file and use it in your page to be similar to the Figma template.

2023-02-16 10:57 UTC, franclobo commented on styles.css
> +body {
- [ ] Please 🙏🏽 use the flexbox to align the content of your page this is a requirement of the project to approve it. This gives us a lot of options to align all our elements, plus, it's responsive.

2023-02-16 10:57 UTC, franclobo commented on index.html
> +                <h2 class="header2">I’m Mariane Glad to see you!</h2>
- [ ] As this is the principal title of your page please 🙏🏽 use the `h1` tag for best practices of HTML & CSS.

2023-02-16 10:57 UTC, franclobo commented on styles.css
> +    display: flex;
- [ ] We don't need yet to specify the media size, please 🙏🏽 remove it because we are going to use it later.

2023-02-16 14:39 UTC, nilab-khwaja commented
updated files

2023-02-16 15:02 UTC, frank1738 requested changes
Hi @nilab-khwaja , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media1.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif"/>

## Highlights

✅ Correct use of Github workflow
✅ No linter error


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
N/A
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-17 11:28 UTC, nilab-khwaja commented
Modify CSS and HTML files

2023-02-17 11:40 UTC, leonardodiasb approved these changes
# Status: ✔️ Project Approved ✔️ 

Hello @nilab-khwaja 🔥 

You worked hard in all the instructions that the previous Code Reviewers give you👍🏽 

Now you can merge this branch 🚀 

## Highlights

 - Good UI matching the Figma template. ✔️ 
 - No linter errors. ✔️ 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-17 12:15 UTC, merged